Repository kresers/firm-app, pull requests merged in 2018-02, with the labels that each got.

#87 help section
  src/app/api-firm.service.ts
  src/app/app.module.ts
  src/app/help/help.component.css
  src/app/help/help.component.html
  src/app/help/help.component.spec.ts
  src/app/help/help.component.ts
  src/app/map/map.component.ts
  src/app/navbar/navbar.component.html
  src/app/top-navbar/top-navbar.component.css
  src/app/top-navbar/top-navbar.component.html
Labels: developement

#88 Correction filter URL
  package-lock.json
  package.json
  src/app/api-firm.service.ts
  src/app/top-navbar/top-navbar.component.html
Labels: bug, developement, done, filters

#91 Features/thomas
  src/app/api-firm.service.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/enterprise/enterprise.component.ts
  src/app/filter-link.service.ts
  src/app/top-navbar/top-navbar.component.html
  src/app/top-navbar/top-navbar.component.ts
Labels: help wanted

#95 add data list filter
  src/app/api-firm.service.ts
  src/app/app.component.html
  src/app/filter-business-categories/filter-business-categories.component.ts
  src/app/filter-code-ape/filter-code-ape.component.html
  src/app/filter-code-ape/filter-code-ape.component.ts
  src/app/filter-creation-year/filter-creation-year.component.ts
  src/app/filter-legal-status/filter-legal-status.component.ts
  src/app/filter-municipality/filter-municipality.component.ts
  src/app/filter-region/filter-region.component.ts
  src/app/filter-total-revenue/filter-total-revenue.component.ts
  src/app/filter-workforce/filter-workforce.component.html
  src/app/filter-workforce/filter-workforce.component.ts
  src/app/loader/loader.component.css
Labels: bug, developement, done, filters, update
